import streamlit as st
import plotly.graph_objects as go
import os
import requests
import joblib 
import pandas as pd
from datetime import datetime
from fpdf import FPDF 
import random 

# =====================================
# 🌸 CUSTOM FLOWER ANIMATION
# =====================================
def show_flower_animation():
    flowers = ['🌸', '🌺', '🌻', '🌼', '🌷']
    html_elements = ""
    for i in range(35):
        f = random.choice(flowers)
        left = random.randint(0, 100)
        duration = random.uniform(3, 6)
        delay = random.uniform(0, 2)
        size = random.uniform(1.2, 2.5)
        html_elements += f'<div class="flower" style="left: {left}%; animation-duration: {duration}s; animation-delay: {delay}s; font-size: {size}rem;">{f}</div>'
    
    css = """
    <style>
    .flower { position: fixed; top: -10%; z-index: 99999; user-select: none; pointer-events: none; animation-name: fall; animation-timing-function: linear; animation-fill-mode: forwards; }
    @keyframes fall { 0% { transform: translateY(-10vh) rotate(0deg) scale(1); opacity: 1; } 100% { transform: translateY(110vh) rotate(360deg) scale(0.8); opacity: 0; } }
    </style>
    """
    st.markdown(css + html_elements, unsafe_allow_html=True)

# =====================================
# 📄 PDF GENERATION FUNCTION (FIXED)
# =====================================
def create_pdf_report(data, weather_dict, ai_label, hero_msg, sub_msg, data_source):
    # 🛠️ THE FIX: This helper function converts text to Latin-1, automatically 
    # dropping any emojis (like 🟢, 💧, ✅) so FPDF doesn't crash!
    def safe_text(val):
        return str(val).encode('latin-1', 'ignore').decode('latin-1').strip()

    clean_hero = safe_text(hero_msg)
    clean_sub = safe_text(sub_msg)
    clean_source = safe_text(data_source) # Strips the 🟢/🟡 circles
    
    pdf = FPDF()
    pdf.add_page()
    
    pdf.set_fill_color(27, 94, 32) 
    pdf.rect(0, 0, 210, 45, 'F')
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", 'B', 24)
    pdf.cell(0, 20, "CROPLY SMART REPORT", ln=True, align='C')
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 5, f"Agricultural Insights | {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align='C')
    
    pdf.ln(25)
    pdf.set_text_color(0, 0, 0)
    
    pdf.set_fill_color(232, 245, 233) 
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 15, f"INSIGHT: {clean_hero}", ln=True, align='C', fill=True)
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 10, f"Analysis: {clean_sub}", align='C', fill=True)
    pdf.ln(10)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.set_fill_color(200, 220, 200)
    pdf.cell(95, 10, "Metric", border=1, fill=True)
    pdf.cell(95, 10, "Value", border=1, ln=True, fill=True)
    
    pdf.set_font("Arial", '', 11)
    
    # 🛠️ Applied safe_text to every value going into the PDF table
    metrics = [
        ("Location", safe_text(data.get('Location', 'N/A'))),
        ("Data Source", clean_source), 
        ("Crop", safe_text(data['Crop Type'])),
        ("Soil Type", safe_text(data['Soil Type'])),
        ("Soil Moisture", f"{data['Moisture']}%"),
        ("Air Temperature", f"{weather_dict['temp']} C"),
        ("Rain Probability", f"{weather_dict['pop']}%"),
        ("N-P-K Levels", f"{data['Nitrogen']}-{data['Phosphorous']}-{data['Potassium']}")
    ]
    
    for item, val in metrics:
        pdf.cell(95, 10, str(item), border=1)
        pdf.cell(95, 10, str(val), border=1, ln=True)

    pdf.ln(10)

    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(27, 94, 32)
    pdf.cell(0, 10, "General Crop Knowledge", ln=True)
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", '', 11)
    care_tips = (f"1. Monitor your {safe_text(data['Crop Type'])} regularly for early signs of pests or nutrient deficiency.\n"
                 f"2. Ensure proper field drainage to avoid root rot, especially if soil moisture exceeds 70%.\n"
                 f"3. Always check local weather forecasts before applying water-soluble fertilizers.")
    pdf.multi_cell(0, 7, care_tips)
    pdf.ln(10)

    pdf.set_font("Arial", 'I', 12)
    pdf.set_text_color(0, 100, 0)
    pdf.multi_cell(0, 8, '"Agriculture is our wisest pursuit, because it will in the end contribute most to real wealth, good morals, and happiness." - Thomas Jefferson', align='C')

    pdf.set_y(-20)
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, "This knowledge report is generated by Croply AI using live sensor and weather data.", align='C')
    
    return bytes(pdf.output(dest='S'))

# =====================================
# 🛠️ BACKEND LINK
# =====================================
try:
    model = joblib.load('random_forest_irrigation_model.pkl')
    target_enc = joblib.load('target_encoder.pkl')
    crop_enc = joblib.load('crop_encoder.pkl')
    soil_enc = joblib.load('soil_encoder.pkl')
    fert_enc = joblib.load('fert_encoder.pkl')
except Exception as e:
    st.error(f"⚠️ Model files missing: {e}")

# 1. Page Configuration
st.set_page_config(page_title="Croply | Recommendation", layout="wide")

# 2. Enhanced CSS
def load_enhanced_styles():
    st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Lexend:wght@300;400;700&family=Poppins:wght@300;400;600&display=swap');
    html, body, [class*="css"] { font-family: 'Poppins', sans-serif; }
    h1, h2, h3 { font-family: 'Lexend', sans-serif; }
    .hero-knowledge { background: linear-gradient(135deg, #1B5E20 0%, #388E3C 100%); color: white; padding: 30px; border-radius: 20px; text-align: center; box-shadow: 0 15px 35px rgba(27, 94, 32, 0.2); margin-bottom: 30px; animation: fadeInDown 0.8s ease-out; position: relative;}
    .hero-label { font-size: 1.2rem; opacity: 0.9; text-transform: uppercase; letter-spacing: 2px; }
    .hero-action { font-size: 2.8rem; font-weight: 700; margin: 10px 0; }
    .data-badge { position: absolute; top: 15px; right: 20px; background: rgba(255,255,255,0.2); padding: 5px 15px; border-radius: 20px; font-size: 0.85rem; font-weight: 600; backdrop-filter: blur(5px);}
    .analysis-card, .weather-card-new { background: white; padding: 25px; border-radius: 20px; box-shadow: 0 8px 20px rgba(0,0,0,0.04); border: 1px solid #E8F5E9; margin-bottom: 20px; }
    .rec-header { color: #1B5E20; font-weight: 700; font-size: 1.3rem; margin-bottom: 15px; display: flex; align-items: center; gap: 10px; }
    @keyframes fadeInDown { from { opacity: 0; transform: translateY(-20px); } to { opacity: 1; transform: translateY(0); } }
    .stButton>button { width: 100%; border-radius: 12px; height: 50px; font-weight: 600; }
    </style>
    """, unsafe_allow_html=True)

load_enhanced_styles()

# 3. Data Retrieval & Logic
if "farm_inputs" not in st.session_state:
    st.error("⚠️ Please enter farm data on the Input Page first!")
    st.stop()

data = st.session_state.farm_inputs
moisture_val = data['Moisture']
city = data.get('Location', 'Mumbai')

def get_weather_description(code):
    mapping = {
        0: "Clear Sky ☀️", 1: "Mainly Clear 🌤️", 2: "Partly Cloudy ⛅", 3: "Overcast ☁️",
        45: "Foggy 🌫️", 48: "Depositing Rime Fog 🌫️", 51: "Light Drizzle 🌦️",
        61: "Slight Rain 🌧️", 63: "Moderate Rain 🌧️", 65: "Heavy Rain ⛈️",
        80: "Slight Rain Showers 🌦️", 95: "Thunderstorm 🌩️"
    }
    return mapping.get(code, "Cloudy ☁️")

def fetch_live_weather(location_name):
    try:
        geo_url = f"https://nominatim.openstreetmap.org/search?q={location_name}&format=json&limit=1"
        geo_res = requests.get(geo_url, headers={'User-Agent': 'CroplyApp/1.0'}, timeout=5).json()
        
        if not geo_res: return None
            
        lat, lon = geo_res[0]['lat'], geo_res[0]['lon']
        
        weather_url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current=temperature_2m,relative_humidity_2m,surface_pressure,wind_speed_10m,weather_code&hourly=precipitation_probability&forecast_days=1&timezone=auto"
        w_data = requests.get(weather_url, timeout=5).json()
            
        current_hour = datetime.now().hour
            
        return {
            "temp": w_data['current']['temperature_2m'], 
            "humidity": w_data['current']['relative_humidity_2m'],
            "pressure": w_data['current']['surface_pressure'], 
            "wind": w_data['current']['wind_speed_10m'],
            "condition": get_weather_description(w_data['current']['weather_code']), 
            "pop": w_data['hourly']['precipitation_probability'][current_hour]
        }
    except Exception as e:
        print(f"Weather Error: {e}")
        return None

with st.spinner(f"Analyzing data for {city}..."):
    weather = fetch_live_weather(city)

# =====================================
# 🔄 THE FALLBACK LOGIC
# =====================================
if weather:
    # API Success
    f_temp, f_humid, f_pres, f_wind, f_cond, f_pop = (
        weather["temp"], weather["humidity"], weather["pressure"], 
        weather["wind"], weather["condition"], weather["pop"]
    )
    api_success = True
    data_source_msg = "🟢 Live Satellite API"
else:
    # API Failed -> Fallback to User Inputs!
    f_temp = data.get('Temperature', 25) 
    f_humid = data.get('Humidity', 50)
    f_pres = "N/A"
    f_wind = "N/A"
    f_cond = "Offline Mode 🔌"
    f_pop = 0 
    api_success = False
    data_source_msg = "🟡 Offline Mode (User Input)"

weather_dict = {"temp": f_temp, "pop": f_pop} 

# AI PREDICTION
soil_num = soil_enc.transform([data['Soil Type']])[0]
crop_num = crop_enc.transform([data['Crop Type']])[0]
fert_num = fert_enc.transform([data.get('Fertilizer Name', 'Urea')])[0]

input_df = pd.DataFrame([[f_temp, f_humid, moisture_val, soil_num, crop_num, data['Nitrogen'], data['Potassium'], data['Phosphorous'], fert_num]], 
                        columns=["Temparature","Humidity","Moisture","Soil Type","Crop Type","Nitrogen","Potassium","Phosphorous","Fertilizer Name"])

prediction = model.predict(input_df)[0]
ai_label = target_enc.inverse_transform([prediction])[0]

# Rain check override
will_rain_soon = api_success and (f_pop > 50)

if ai_label == "NONE": hero_msg, sub_msg, status_icon = "✅ MOISTURE OPTIMAL", "No irrigation required at this time.", "🌿"
elif will_rain_soon: hero_msg, sub_msg, status_icon = "⚠️ POSTPONE FOR RAIN", f"Model suggests irrigation, but {f_pop}% rain chance detected.", "🌦️"
else: hero_msg, sub_msg, status_icon = f"💧 {ai_label} IRRIGATION", f"AI recommends applying water based on {data['Crop Type']} needs.", "🚜"

# =====================================
# 🚀 VISUAL OUTPUT
# =====================================

st.markdown(f"""
    <div class="hero-knowledge">
        <div class="data-badge">{data_source_msg}</div>
        <div class="hero-label">AI Smart Recommendation</div>
        <div class="hero-action">{status_icon} {hero_msg}</div>
        <div style="font-size: 1.2rem; opacity: 0.9;">{sub_msg}</div>
    </div>
""", unsafe_allow_html=True)

col_left, col_right = st.columns([1, 1.2], gap="large")

with col_left:
    fig = go.Figure(go.Indicator(
        mode = "gauge+number", value = moisture_val,
        title = {'text': "Current Soil Moisture", 'font': {'size': 20}},
        number = {'suffix': "%", 'font': {'color': '#1B5E20'}},
        gauge = {'axis': {'range': [0, 100]}, 'bar': {'color': "#2E7D32"}, 'steps': [{'range': [0, 30], 'color': "#FFEBEE"}, {'range': [30, 70], 'color': "#FFFDE7"}, {'range': [70, 100], 'color': "#E8F5E9"}]}
    ))
    fig.update_layout(height=350, margin=dict(l=20, r=20, t=40, b=20), paper_bgcolor='rgba(0,0,0,0)')
    st.plotly_chart(fig, use_container_width=True)

    st.markdown(f"""
        <div class="weather-card-new">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px;">
                <div class="rec-header" style="margin-bottom: 0;">☁️ Local Forecast: {city}</div>
            </div>
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <span style="font-size: 2rem;">{f_cond.split()[-1] if len(f_cond.split()) > 0 else f_cond}</span>
                <span style="font-size: 1.5rem; font-weight: bold; color: #1B5E20;">{f_temp}°C</span>
            </div>
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-top: 15px; font-size: 0.9rem; color: #666;">
                <span>💧 Humidity: <b>{f_humid}%</b></span><span>💨 Wind: <b>{f_wind}{' km/h' if f_wind != 'N/A' else ''}</b></span>
                <span>🌧️ Rain Chance: <b>{f_pop}%</b></span><span>⏲️ Pressure: <b>{f_pres}{' hPa' if f_pres != 'N/A' else ''}</b></span>
            </div>
        </div>
    """, unsafe_allow_html=True)

with col_right:
    st.markdown("""<div class="rec-header">📊 Nutrient Knowledge Chart</div>""", unsafe_allow_html=True)
    
    crop = data.get('Crop Type', 'Wheat')
    ideal_npk_mapping = {
        'Maize': (120, 60, 40), 'Sugarcane': (250, 100, 100), 'Cotton': (150, 60, 90),
        'Tobacco': (110, 50, 50), 'Paddy': (120, 60, 40), 'Barley': (60, 30, 20),
        'Wheat': (120, 60, 40), 'Millets': (60, 40, 20), 'Oil seeds': (60, 40, 40),
        'Pulses': (20, 60, 20), 'Ground Nuts': (20, 50, 40)
    }
    
    ideal_n, ideal_p, ideal_k = ideal_npk_mapping.get(crop, (100, 50, 50))
    
    fig_npk = go.Figure(data=[
        go.Bar(name='Current (Your Soil)', x=['Nitrogen (N)', 'Phosphorous (P)', 'Potassium (K)'], y=[data['Nitrogen'], data['Phosphorous'], data['Potassium']], marker_color='#388E3C'),
        go.Bar(name=f'Ideal for {data["Crop Type"]}', x=['Nitrogen (N)', 'Phosphorous (P)', 'Potassium (K)'], y=[ideal_n, ideal_p, ideal_k], marker_color='#E0E0E0')
    ])
    fig_npk.update_layout(barmode='group', height=250, margin=dict(l=10, r=10, t=30, b=10), paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1))
    st.plotly_chart(fig_npk, use_container_width=True)
    
    st.markdown(f"""
        <div class="analysis-card" style="border-left: 5px solid #1B5E20; margin-top: 10px;">
            <div class="rec-header">📖 Action Insights</div>
            <p style="font-size: 0.95rem; line-height: 1.6; color: #333;">
                Watering is currently <b>{'not recommended (incoming rain)' if will_rain_soon else ai_label.lower()}</b>. 
                {sub_msg} Monitor your N-P-K levels against the grey baseline above to optimize fertilizer use.
            </p>
        </div>
    """, unsafe_allow_html=True)

st.write("---")

# --- NEW: EDUCATIONAL SECTION ---
st.markdown("### 📚 Crop & Soil Education Center")
col_edu1, col_edu2 = st.columns(2)

with col_edu1:
    with st.expander(f"🌱 Optimal Conditions for {data['Crop Type']}"):
        st.write(f"""
        **Did you know?** {data['Crop Type']} thrives best when soil moisture is carefully balanced. 
        * **Nutrients:** Requires a steady supply of Nitrogen during vegetative growth.
        * **Warning Signs:** Yellowing leaves might indicate a Nitrogen deficiency or over-watering.
        """)

with col_edu2:
    with st.expander(f"🪨 Understanding {data['Soil Type']} Soil"):
        st.write(f"""
        **Soil Profile:** {data['Soil Type']} soils have unique water retention properties. 
        * **Irrigation Tip:** Adjust your watering frequency based on how fast this specific soil type drains. 
        * **Fertilizer:** Ensure your {data.get('Fertilizer Name', 'fertilizer')} mixes well with this soil's natural pH structure.
        """)

st.write("###")

pdf_bytes = create_pdf_report(data, weather_dict, ai_label, hero_msg, sub_msg, data_source_msg)

btn_col1, btn_col2 = st.columns(2)
with btn_col1:
    if st.download_button(label="📥 Download Report (PDF)", data=pdf_bytes, file_name=f"Croply_Knowledge_{city}.pdf", mime="application/pdf"):
        st.session_state.downloaded = True

with btn_col2:
    if st.button("🔄 New Analysis"):
        st.switch_page("pages/1_input_page.py")

if st.session_state.get('downloaded'):
    show_flower_animation()
    st.success("✅ **Download Complete!** Your Knowledge Hub report has been securely generated and saved to your device.")
    st.toast("📄 Professional PDF Report saved successfully!", icon="✅")
    st.session_state.downloaded = False